/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface TimerComponent {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTimerComponentElement extends Components.TimerComponent, HTMLStencilElement {}
  var HTMLTimerComponentElement: {
    prototype: HTMLTimerComponentElement;
    new (): HTMLTimerComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'timer-component': HTMLTimerComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface TimerComponent extends JSXBase.HTMLAttributes<HTMLTimerComponentElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'timer-component': TimerComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


